name: Node.js CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upgrade NPM
        run: npm install -g npm
      - name: copy-config
        run: cp src/configuration/configuration.example.tsx src/configuration/configuration.tsx
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'
      - run: npm install
      - run: npm run build

